2023-10-18 10:19:04,956 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-18 10:19:29,697 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-18 10:28:38,029 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-18 10:39:22,783 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-18 10:57:22,592 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-18 10:57:36,823 [ERROR] django.request: Internal Server Error: /history/
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\python-django-team27-dGGw-sPd-py3.11\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\python-django-team27-dGGw-sPd-py3.11\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\python-django-team27-dGGw-sPd-py3.11\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\python-django-team27-dGGw-sPd-py3.11\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\python-django-team27-dGGw-sPd-py3.11\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\python-django-team27-dGGw-sPd-py3.11\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: history/browsinghistory_list.html
2023-10-18 10:57:36,991 [WARNING] django.request: Not Found: /favicon.ico
2023-10-18 10:58:43,387 [INFO] django.utils.autoreload: C:\OwnFinal\market\history\views.py changed, reloading.
2023-10-18 10:58:44,857 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-18 11:02:33,261 [INFO] django.utils.autoreload: C:\OwnFinal\market\history\views.py changed, reloading.
2023-10-18 11:02:34,775 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-18 11:03:09,276 [INFO] django.utils.autoreload: C:\OwnFinal\market\history\views.py changed, reloading.
2023-10-18 11:03:11,198 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-19 18:22:35,611 [WARNING] django.request: Not Found: /api/v1/order/status/50
